import java.awt.event.KeyEvent;
import java.awt.*;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MEYSAM
 */
public class TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
        lblTurn.setText("Turn Of "+sign);
        lblTurn.setOpaque(true);
        this.getContentPane().setBackground(Color.YELLOW);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        lblTurn = new javax.swing.JLabel();
        btnRestart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicTacToe");
        setBackground(new java.awt.Color(255, 255, 102));
        setResizable(false);

        btn1.setBackground(new java.awt.Color(0, 204, 204));
        btn1.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        btn1.setFocusPainted(false);
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCellAction(evt);
            }
        });
        btn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnKeyPressedAction(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(0, 204, 204));
        btn2.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        btn2.setFocusPainted(false);
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCellAction(evt);
            }
        });
        btn2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnKeyPressedAction(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(0, 204, 204));
        btn3.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        btn3.setFocusPainted(false);
        btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCellAction(evt);
            }
        });
        btn3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnKeyPressedAction(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(0, 204, 204));
        btn6.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        btn6.setFocusPainted(false);
        btn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCellAction(evt);
            }
        });
        btn6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnKeyPressedAction(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(0, 204, 204));
        btn5.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        btn5.setFocusPainted(false);
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCellAction(evt);
            }
        });
        btn5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnKeyPressedAction(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(0, 204, 204));
        btn4.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        btn4.setFocusPainted(false);
        btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCellAction(evt);
            }
        });
        btn4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnKeyPressedAction(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(0, 204, 204));
        btn9.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        btn9.setFocusPainted(false);
        btn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCellAction(evt);
            }
        });
        btn9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnKeyPressedAction(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(0, 204, 204));
        btn8.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        btn8.setFocusPainted(false);
        btn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCellAction(evt);
            }
        });
        btn8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnKeyPressedAction(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(0, 204, 204));
        btn7.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        btn7.setFocusPainted(false);
        btn7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCellAction(evt);
            }
        });
        btn7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnKeyPressedAction(evt);
            }
        });

        lblTurn.setBackground(new java.awt.Color(0, 255, 51));
        lblTurn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTurn.setForeground(new java.awt.Color(255, 0, 0));
        lblTurn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTurn.setToolTipText("");
        lblTurn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        btnRestart.setBackground(new java.awt.Color(255, 122, 247));
        btnRestart.setText("Restart");
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRestart, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String sign="X";
    String state="";
    
    private void btnCellAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCellAction
        
        JButton btn=(JButton) evt.getSource();
        if(!btn.getText().isEmpty()) return;
        {
        btn.setText(sign);
        if(sign.equals("X"))
          sign="O";
        else
            sign="X";
        }
        
        if(btn1.getText().equals("X")&&btn2.getText().equals("X")&&btn3.getText().equals("X"))
        {state="X Won";}
        
        if(btn3.getText().equals("X")&&btn6.getText().equals("X")&&btn9.getText().equals("X"))
        {state="X Won";}
        
        if(btn7.getText().equals("X")&&btn8.getText().equals("X")&&btn9.getText().equals("X"))
        {state="X Won";}
        
        if(btn1.getText().equals("X")&&btn4.getText().equals("X")&&btn7.getText().equals("X"))
        {state="X Won";}
        
        if(btn1.getText().equals("X")&&btn5.getText().equals("X")&&btn9.getText().equals("X"))
        {state="X Won";}
        
        if(btn3.getText().equals("X")&&btn5.getText().equals("X")&&btn7.getText().equals("X"))
        {state="X Won";}
        
        if(btn2.getText().equals("X")&&btn5.getText().equals("X")&&btn8.getText().equals("X"))
        {state="X Won";}
        
        if(btn4.getText().equals("X")&&btn5.getText().equals("X")&&btn6.getText().equals("X"))
        {state="X Won";}
        
        /////////////////////////////////////////////////////////////////////////////////////
        
        if(btn1.getText().equals("O")&&btn2.getText().equals("O")&&btn3.getText().equals("O"))
        {state="O Won";}
        
        if(btn3.getText().equals("O")&&btn6.getText().equals("O")&&btn9.getText().equals("O"))
        {state="O Won";}
        
        if(btn7.getText().equals("O")&&btn8.getText().equals("O")&&btn9.getText().equals("O"))
        {state="O Won";}
        
        if(btn1.getText().equals("O")&&btn4.getText().equals("O")&&btn7.getText().equals("O"))
        {state="O Won";}
        
        if(btn1.getText().equals("O")&&btn5.getText().equals("O")&&btn9.getText().equals("O"))
        {state="O Won";}
        
        if(btn3.getText().equals("O")&&btn5.getText().equals("O")&&btn7.getText().equals("O"))
        {state="O Won";}
        
        if(btn2.getText().equals("O")&&btn5.getText().equals("O")&&btn8.getText().equals("O"))
        {state="O Won";}
        
        if(btn4.getText().equals("O")&&btn5.getText().equals("O")&&btn6.getText().equals("O"))
        {state="O Won";}
        
        if(!btn1.getText().isEmpty()&&!btn2.getText().isEmpty()&&!btn3.getText().isEmpty()
         &&!btn4.getText().isEmpty()&&!btn5.getText().isEmpty()&&!btn6.getText().isEmpty()
         &&!btn7.getText().isEmpty()&&!btn8.getText().isEmpty()&&!btn9.getText().isEmpty()&&state.equals(""))
        {
            state="Draw!";
        }
        
        if(!state.isEmpty()) showMessage();
        lblTurn.setText("Turn Of "+sign);
    }//GEN-LAST:event_btnCellAction

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        Clear();
        lblTurn.setText("Turn Of "+sign);
    }//GEN-LAST:event_btnRestartActionPerformed

    private void btnKeyPressedAction(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnKeyPressedAction
        
        String keyText=String.valueOf(evt.getKeyChar());//KeyEvent.getKeyText(evt.getKeyCode());
        
        switch (keyText)
        {
            case "1":
                btn1.doClick();
                break;
                
            case "2":
                btn2.doClick();
                break;
                
            case "3":
            btn3.doClick();
            break;
                    
            case "4":
            btn4.doClick();
            break;
                        
            case "5":
            btn5.doClick();
            break;
                        
            case "6":
            btn6.doClick();
            break;
                                
            case "7":
            btn7.doClick();
            break;
                                    
            case "8":
            btn8.doClick();
            break;
                                        
            case "9":
            btn9.doClick();
            break;
                                             
        }
    }//GEN-LAST:event_btnKeyPressedAction

    private void showMessage()
    {
      int i=JOptionPane.showOptionDialog(null,
              state+" , For A New Game Select Ok",
              "Message",
              0,
              JOptionPane.INFORMATION_MESSAGE,
              null,
              new String[]{"Ok"},
              null);
      
      if(i==0||i==-1) Clear(); 
      
      
    }
    
    private void Clear()
    {
        btn1.setText("");
        btn2.setText("");
        btn3.setText("");
        btn4.setText("");
        btn5.setText("");
        btn6.setText("");
        btn7.setText("");
        btn8.setText("");
        btn9.setText("");
        lblTurn.setText("");
        state="";
        sign="X";
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnRestart;
    private javax.swing.JLabel lblTurn;
    // End of variables declaration//GEN-END:variables
}
